name = "Academic"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-academic/blob/master/LICENSE.md"
description = "Use the website builder to personalize your academic resumé with widgets and deploy with one click! Fully customize your site with themes, plugins, and language packs."
homepage = "https://wowchemy.com"
min_version = "0.73"
tags = ["widgets",
        "resume",
        "portfolio",
        "responsive",
        "clean",
        "personal",
        "company",
        "blog",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "documentation",
        "landing page",
        "projects",
        "single page",
        "contact form",
        "mobile",
        "gallery",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "product",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
# Theme metadata
name = "my_theme"

# Is theme light or dark?
light = dark

# Primary
primary = "#EF476F"

# Menu
menu_primary = "#F7F7F7"
menu_text = "#FCA311"
menu_text_active = "#0EAD69"
menu_title = "#118AB2"

# Backgrounds
background = "#F7F7F7"
home_section_odd = "#F7F7F7"
home_section_even = "#F7F7F7"

dark_background = ""
dark_home_section_odd = ""
dark_home_section_even = ""

link = "#D90429"
link_hover = "#118AB2"
