---
title: "What is Model?"
author: "Saurav Das"
date: '2020-10-17'
slug: what-is-model
categories: statistics
tags:
- model
- statistics
---

So, when start discussion or thinking about model, some complex equation or some mathematical derivation comes to your mind, but for now lets start this things from a simple definition 

# 1. What is "Model" ?

## The most common thing about model is "A model is a representation for a particular thing with particular purpose"

we have been exposed/experienced or used different kinds of models from our childhood. Lets say, a toy, a toy is a representation of particular animal/tree or humans, but its not the real or true animal, its a representation of a particular animal.

A model may be physical or just an idea, but it always stands for something else: ***its a representation***.

When you create a model you always start with a **purpose** in your mind. Like the purpose of toys is to entertain kids.

Model always miss out few things, get some more thing, many things goes wrong.So, for model there is no need for a question like ***is the model true ?***, if truth is to be the whole truth the answer will be no. The model is only representation and the question of interest should ***is the model useful?*** A good model is close to the thing its trying to represent.

<b><i><h4> George Box told all models are wrong but some are useful </b></i></h4>

Statistical models generally revolve around data. There are three main uses/purpose of statistical models.

1. ***Description*** - It can be used to describe the values and relationship among the data. For eg. Relationship between the high gasoline price and sell of car.

2. ***Prediction*** - It can be used to predict something based on observable traits, qualities or attributes. For eg. You have a patients blood sugar level, blood pressure level, and other laboratory measurements, now you want to predict or proper word here will be diagnose the patient illness.

3. ***Consequences/Making decisions*** - Now you are active participant in the model making the decisions based on your model predictions. For eg. To what extent will paying teachers more increase student performance ?


####Okay, now before heading directly towards doing modeling, lets discuss some basic terms like variables, samples etc.











